run = ["bash", "quick_run.sh"]
entrypoint = "simple_app.py"
hidden = [".config", ".env", "logs", "__pycache__", ".git"]

[env]
PYTHONUNBUFFERED = "1"
PUBLIC_ACCESS = "true"
PORT = "8080"
SESSION_SECRET = "nous-secure-key-2025"

[nix]
channel = "stable-22_11"

[packager]
language = "python3"

[packager.features]
enabledForHosting = true
packageSearch = true
guessImports = true

[unitTest]
language = "python3"

[languages.python3]
pattern = "**/*.py"
syntax = "python"

[languages.python3.languageServer]
start = ["pylsp"]

[deployment]
run = ["bash", "quick_run.sh"]
deploymentTarget = "cloudrun"
publicDir = "/"
ignorePorts = false

[auth]
pageEnabled = false
buttonEnabled = false