[run]
command = "bash public_start.sh"

[deployment]
run = ["sh", "-c", "bash public_deploy.sh"]
deploymentTarget = "cloudrun"
ignorePorts = false

[periodic-jobs]
monitor = { cron = "*/15 * * * *", command = "bash monitor_deploy.sh" }

[env]
PORT = "8080"
FLASK_APP = "main.py"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"

[languages.python]
pattern = "**/*.py"

[nix]
channel = "stable-24_05"

[unitTest]
language = "python"

[auth]
pageEnabled = false
buttonEnabled = false